name: fakebook

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
#    networks:
#      - fakebook_network

  api:
    image: fakebook_api
    container_name: api
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - MINIO_BUCKET=fakebook
      - MINIO_ACCESS_KEY=12345678
      - MINIO_SECRET_KEY=12345678
      - MINIO_HOST=10.29.117.119
      - MINIO_PORT=9000
    ports:
      - "3000:3000"
    depends_on:
      - db
      - minio
#    networks:
#      - fakebook_network

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=adminadmin
      - MINIO_ROOT_PASSWORD=adminadmin
      - MINIO_DOMAIN=192.168.1.100
      - MINIO_SERVER_URL=http://127.0.0.1:9000
    ports:
      - "9000:9000"
      - "9001:9001"
    ##networks:
    ##  - fakebook_network
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:

#networks:
#  fakebook_network:
#    driver: bridge
    
